# Generated by Django 5.1.2 on 2024-10-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to='places/')),
                ('image_alt_text', models.CharField(default='product image', max_length=1000)),
                ('image_url', models.URLField(max_length=1000, null=True)),
                ('description_eng', models.TextField(null=True)),
                ('name_eng', models.CharField(null=True)),
                ('url', models.CharField(null=True)),
                ('description_fin', models.TextField(null=True)),
                ('name_fin', models.CharField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postal_code', models.IntegerField()),
                ('street_name', models.CharField()),
                ('city', models.CharField()),
                ('available_time', models.CharField()),
                ('price', models.CharField()),
            ],
        ),
    ]
