# Generated by Django 5.0b1 on 2024-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField()),
                ('image_alt_text', models.CharField(default='product image')),
                ('image_url', models.CharField(null=True)),
                ('description_eng', models.TextField(null=True)),
                ('name_eng', models.CharField(null=True)),
                ('url', models.CharField(null=True)),
                ('description_fin', models.TextField(null=True)),
                ('name_fin', models.CharField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postal_code', models.IntegerField()),
                ('street_name', models.CharField()),
                ('city', models.CharField()),
                ('available_time', models.CharField()),
                ('price', models.CharField()),
            ],
        ),
    ]
