# Generated by Django 5.0b1 on 2024-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
