# Generated by Django 5.0b1 on 2024-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.ImageField(upload_to='places/images/'),
        ),
    ]
