services:
  db:
    image: postgres:latest
    container_name: finnhike_db
    expose:
      - "5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_NAME_DEV}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finnhike_web:
    build:
      context: .
      dockerfile: DockerfileDev
    command: python manage.py runserver 0.0.0.0:8000
    container_name: finnhike_web
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  postgres_data: {}