services:
  db:
    image: postgres:latest
    container_name: finnhike_db
    expose:
      - "5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finnhike_web:
    build: .
    command: gunicorn finnhike.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./static_volume:/app/static
      - ./media_volume:/app/media
    container_name: finnhike_web
    env_file: .env
    environment:
      - FINHIKE=prod
    ports:
      - 8000:8000
    links:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static_volume:/static
      - ./media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - finnhike_web
    links:
      - finnhike_web


volumes:
  postgres_data: {}
  static_volume:
  media_volume: