services:
  finnhike_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    container_name: finnhike_web
    env_file: .env
    environment:
      - FINHIKE=prod
    ports:
      - "8000:8000"
    networks:
      - finnhike_net

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    ports:
      - "80:8080"
    depends_on:
      - finnhike_web
    links:
      - finnhike_web
    networks:
      - finnhike_net


volumes:
  postgres_data: {}
  static_volume: {}
  media_volume: {}

networks:
  finnhike_net: