services:
  db:
    image: postgres:latest
    container_name: finnhike_db
    expose:
      - "5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finnhike_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    container_name: finnhike_web
    env_file: .env
    ports:
      - 8000:8000
    links:
      - db
    restart: always

volumes:
  postgres_data: {}