services:
  finnhike_web:
    build: ./
    container_name: finnhike_web_cont
    restart: always
    command: bash entrypoint.sh
    volumes:
      - ./app_code:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - finnhike_db

  finnhike_db:
    image: postgres:latest
    container_name: finnhike_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: